version: "3.9"
services:
  app:
    build: ./infra/php
    volumes:
      - ./src:/data
    # Laravelでviteを使用して開発する際に必要（viteの開発サーバーのデフォルトポートに合わせる）
    ports:
      - 5173:5173
  web:
    image: nginx:1.22-alpine
    ports:
      - 8080:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  db:
    build: ./infra/mysql
    # ローカル環境からDBにアクセスするための設定
    ports:
      - "3309:3306"
    volumes:
      - db-store:/var/lib/mysql

volumes:
  db-store: